### ISSUE TITLE
Mutual Information metric raises error if fn_tp = 0

### ISSUE THREAD

**Issue by riedj1** [rundherum/pymia#3]
In MI, the h1 and h2 calculations may raise errors in certain cases:

when both fn and tp are zero (all positives), math.log2(fn_tp / n) fails. same goes for fp_tn

**Comment by soomy** [comment]
If I remember correctly the same kind of error happens when using the Hausdorff distance metric with an all-zero segmentation mask.

**Comment by riedj1** [comment]
Yes, it does, as well as in AverageDistance. But per definition it
> Computes the Hausdorff distance between the set of non-zero pixels of two images.
[https://itk.org/Doxygen/html/classitk_1_1HausdorffDistanceImageFilter.html](url)

So raising an error in case someone has a zero mask is not wrong, just not convenient

**Comment by fabianbalsiger** [comment]
I have been thinking about this. I see two ways how we could address non-computable metrics: 1) raising an error or 2) raising a warning and returning the worst value this metric would calculate.

1) We would define a Runtime**Error** and rise it. This might be the cleanest way but not so convenient since it can easily happen that e.g. the segmentation is all-zero early in the training. This would force people to handle these cases by themselves e.g. in the `Evaluator` class. 

```
class NotComputableMetricError(RuntimeError):
    """
    Exception class to raise if a metric cannot be computed.
    """
```

2) We would define a Runtime**Warning** and rise it. The leaves us to define what values we would return for e.g. a non-computable Hausdorff distance.
```
class NotComputableMetricWarning(RuntimeWarning):
    """
    Warning class to raise if a metric cannot be computed.
    """
```

I prefer solution 1). In that case, we do not return any made up values, which might end up in a paper in the worst case scenario... Any other solutions? What do you think @alainjungo ?

**Comment by fabianbalsiger** [comment]
Metrics now raise a `NotComputableMetricWarning` and return `float('inf')` or `float('-inf')` but code continues to run.
