### ISSUE TITLE
[enhancement] explorative label mode

### ISSUE THREAD

**Issue by neuronflow** [rundherum/pymia#30]
instead of adding labels manually with code like:
```
    evaluator.add_label(1, 'necrosis')
    evaluator.add_label(2, 'edema')
    evaluator.add_label(4, 'enhancing')
```

it would be cool if there was a mode where the evaluator analyzes all labels it finds. This would be cool for explorative analysis of messy datasets and to detect errors / mistakes in code.

**Comment by fabianbalsiger** [comment]
Hi, I think this functionality is too specific and, therefore, out of scope for the library.
But it should be fairly easy to implement, just copy the `Evaluator` class, and replace the [for-loop](https://github.com/rundherum/pymia/blob/634a12978e1531f34b609560e10c0716130d168d/pymia/evaluation/evaluator.py#L235) in `evaluate()` by something like

```
for label in np.unique(ground_truth_array):
    label_str = f'LBL{label}'

```

Hope this helps.

**Comment by neuronflow** [comment]
hmm your proposed solution works for extra labels inside the GT but does not capture labels which are only present only on the segmentation side.

**Comment by fabianbalsiger** [comment]
indeed, but then you could replace `ground_truth_array` with `image_array`. Actually this shows the problem of implementing such a feature, the cases to handle are quite diverse and in my opinion, it is not the purpose of the evaluator to do this. Maybe instead of implementing the evaluator, you could do a sanity check before calling `evaluate()`. This sanity check could then adapt the labels (`evaluator.labels = <labels the sanity check thinks would be useful to evaluate>`) before calling `evaluate()`.
