### ISSUE TITLE
[Question] is there a way to evaluate all labels present in the data?

### ISSUE THREAD

**Issue by neuronflow** [rundherum/pymia#38]
[Question] is there a way to evaluate all labels present in the data?

I did not find it in the documentation.

if not it would be lovely to have it.

**Comment by fabianbalsiger** [comment]
Do you mean that every subject will have a different amount of labels? Usually, you will know the labels upfront, that's why you pass the `labels` to the `SegmentationEvaluator`, as shown in this [example](https://pymia.readthedocs.io/en/latest/examples.evaluation.basic.html).

If you need "adaptable" labels, you could set the `SegmentationEvaluator.labels` manually every time before calling `SegmentationEvaluator.evaluate()`. Or you reimplement the `SegmentationEvaluator` and change the `self.labels` before the loop at [this line](https://github.com/rundherum/pymia/blob/142842e322b2f712aa45850f23f4875dc2c0f493/pymia/evaluation/evaluator.py#L111), e.g. using `np.unique(reference_array)` and then convert the array to a dict.

Does this help?

**Comment by neuronflow** [comment]
Currently I am trying to process a spine CT dataset. Some of the exams contain vertebrae 1-26 some only a subset, e.g. 1-9 or less. This also heavily distorts average calculcations.

**Comment by fabianbalsiger** [comment]
Ok, so I think both of the two solutions are appropriate for your use case and are straightforward to realize. As you mention the proceeding aggregation of the results also might need adaptation, which is very task-dependent, so it might be hard to easily implement this as a standard feature.
