### ISSUE TITLE
pymia.data.transformation.py

### ISSUE THREAD

**Issue by zhuzhanshi** [rundherum/pymia#47]
there is a function, named `SizeCorrection(Transform)`.
Only padding the array. but the property in the sample list is not changed, especially the 'shape'.

It is a sample in my code.
The size is correct to 256x256 from 240x256, but the 'shape' property is still 240x256. Thus, some bugs in my code.

Could you consider updating this function?  Add the function about correcting the property.

**Comment by fabianbalsiger** [comment]
Hi

This behaviour is because you might need to know the original shape (e.g., for assembling back to the original space). In other words, you can always get the actual size of the current tensor by numpy/Pytorch size functions (e.g., array.shape). But once you overwrite the shape property, you don't know anymore that it actually was 240x256... Does that make sense?

Best,
Fabian

**Comment by zhuzhanshi** [comment]
Thank you I know what you mean.

**Comment by fabianbalsiger** [comment]
Cool! Of course, you can always write your own `SizeCorrection`. I would then recommend creating a new entry and not overwriting the shape entry, e.g., `sample['shape_corrected'] = np_entry.shape` rather than `sample['shape'] = np_entry.shape`. Otherwise, the functionality of other features might break.

I am closing this issue, feel free to reopen it when you have other questions. Thanks!

Best, Fabian
